version: '3'

services:
  prisma:
    image: postgres
    container_name: reviewsdb
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=prismacontainer
      - POSTGRES_DB=reviewsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: