version: '3'

services:
  prisma:
    image: postgres
    container_name: reviewsdb
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
